name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "🚀 Starting deployment script..."

            cd smart-air-port

            echo "📦 Stashing any local changes..."
            git stash || true

            echo "⬇️ Pulling latest code from main branch..."
            git pull origin main --rebase

            echo "📤 Re-applying local changes (if any)..."
            git stash pop || true

            echo "🔧 Exporting bun path..."
            export PATH="$HOME/.bun/bin:$PATH"

            echo "🔨 Building the application..."
            bun run build

            echo "♻️ Restarting application with PM2..."
            pm2 restart smart-airport

            echo "✅ Deployment finished successfully!"
