name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App on Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH as alijs
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            sudo su - alijs << 'INNER'
              cd /home/alijs/smart-air-port
              git pull origin main
              bun install
              bun run build
              pm2 restart smart-airport
            INNER
          EOF
