name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App on Azure VM
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH as alijs
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            # Fix git ownership and permissions issues
            cd /home/alijs
            sudo chown -R alijs:alijs smart-air-port
            sudo chmod -R 755 smart-air-port
            cd smart-air-port
            
            # Configure git to trust this directory
            git config --global --add safe.directory /home/alijs/smart-air-port
            
            # Pull latest changes
            git pull origin main
            
            # Check if node_modules exists, install if not
            if [ ! -d "node_modules" ]; then
              echo "Installing dependencies..."
              bun install
            else
              echo "Updating dependencies..."
              bun install
            fi
            
            # Build with verbose output and timeout
            echo "Starting build process..."
            timeout 300 bun run build:ci || { echo "Build timed out after 5 minutes"; exit 1; }
            
            # Restart the application with PM2
            echo "Restarting application..."
            pm2 restart smart-airport || pm2 start dist/main.js --name smart-airport
            
            # Check application status
            echo "Application status:"
            pm2 status
          EOF
